spring:
  main:
    web-application-type: none   # 非 Web 模式, 不启动 Tomcat
    headless: false              # 允许 JavaFX GUI
    banner-mode: off             # 关闭启动横幅
  application:
    name: Jcurl2

# Jcurl2 自定义配置
jcurl2:
  # 数据存储根目录(默认用户主目录下 .api-client)
  data-dir: ${user.home}/.api-client
  # 历史记录上限
  history-limit: 500
  # 默认主题: light / dark
  theme: dark
